# Generated by Django 5.2.3 on 2025-06-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.SmallIntegerField(choices=[(1, 'Unpaid'), (2, 'Paid')], default=1, max_length=20),
        ),
    ]
