# Generated by Django 5.2.3 on 2025-06-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('segment', models.CharField(choices=[(1, 'New Customer'), (2, 'Regular Customer'), (3, 'VIP Customer'), (4, 'Inactive Customer')], max_length=1)),
                ('orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
