# Generated by Django 5.2.3 on 2025-06-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_last_purchase_customer_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='last_purchase',
            new_name='last_purchase_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='segment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New Customer'), (2, 'Regular Customer'), (3, 'VIP Customer'), (4, 'Inactive Customer')], default=1),
        ),
    ]
