# Generated by Django 5.2.3 on 2025-06-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_last_purchase_customer_last_purchase_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_purchase_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='segment',
            field=models.CharField(choices=[(1, 'New Customer'), (2, 'Regular Customer'), (3, 'VIP Customer'), (4, 'Inactive Customer')], max_length=1),
        ),
    ]
