# Generated by Django 5.2.3 on 2025-06-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_last_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='segment',
            field=models.SmallIntegerField(choices=[(1, 'New Customer'), (2, 'Regular Customer'), (3, 'VIP Customer'), (4, 'Inactive Customer')], default=1, max_length=1),
        ),
    ]
